apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{.Chart.Name | quote}}
  labels:
{{ include "commonLabels" .  | indent 4}}
rules:
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
  - update
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs:
  - list
  - watch
  - update
