apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{.Chart.Name | quote}}
  labels:
    app: {{.Chart.Name | quote}}
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
    {{- end }}
rules:
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
  - update
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs:
  - list
  - watch
  - update
