apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Chart.Name | quote}}
  namespace: {{.Release.Namespace | quote}}
  {{- include "labels" . | indent 2}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{.Chart.Name | quote}}
  template:
    metadata:
      {{- include "labels" . | indent 6}}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      serviceAccount: {{.Chart.Name | quote}}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values:
                - "true"
      containers:
      - name: {{.Chart.Name | quote}}
        image: estafette/estafette-k8s-hpa-scaler:{{.Chart.AppVersion}}
        imagePullPolicy: Always
        env:
        - name: "PROMETHEUS_SERVER_URL"
          value: {{.Values.variables.prometheus_url | quote}}
        - name: "MINIMUM_REPLICAS_LOWER_BOUND"
          value: {{.Values.variables.min_replicas_lower_bound | quote}}
        resources:
          requests:
            cpu: {{.Values.resources.requests.cpu | quote}}
            memory: {{.Values.resources.requests.memory | quote}}
          limits:
            cpu: {{.Values.resources.limits.cpu | quote}}
            memory: {{.Values.resources.limits.memory | quote}}
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9101
          initialDelaySeconds: 30
          timeoutSeconds: 1
