apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{.Chart.Name | quote}}
  labels:
    app: {{.Chart.Name | quote}}
rules:
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
  - update
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs:
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{.Chart.Name | quote}}
  labels:
    app: {{.Chart.Name | quote}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Chart.Name | quote}}
subjects:
- kind: ServiceAccount
  name: {{.Chart.Name | quote}}
  namespace: {{.Release.Namespace | quote}}
